
### These codes are used to stack all velocity geo-tif files generated from Matlab codes ###
### After Stacking, we will also extract velocity values from the stacked files ###


# load the relevant Library

library(raster)
library(sp)
library(rgdal)
library(gdalUtils)
library(gdalUtilities)
library(RStoolbox)

## Set working directory and define the work folder for 10 meter

setwd("C:/Users/Advice/OneDrive - Victoria University of Wellington - STUDENT/GISC 511/ImGraft/Tasman_Deresolution_Velocity")

workfolder_5 <- "./5 meters"
workfolder_10 <- "./10 meters"
workfolder_20 <- "./20 meters"
workfolder_30 <- "./30 meters"

## 28-Oct-2020 ## Franz Josef Glaciers.


#### Extract velocity values from this period of times (Oct 2020 - Oct 2020) - Tasman glacier 

## Read the stacked raster that contains all velocity compared between scences generated by using Matlab - Imgraft Package.
velocity_stack_5 <- stack(file.path(workfolder_5, "velocity_stack.tif"))
velocity_stack_10  <- stack(file.path(workfolder_10, "velocity_stack.tif"))
velocity_stack_20  <- stack(file.path(workfolder_20, "velocity_stack.tif"))
velocity_stack_30  <- stack(file.path(workfolder_30, "velocity_stack.tif"))

## Also read the the shapefile of the interested points in the lower parts of Tasman glacier.

pointCoordinates=readOGR("C:/Users/Advice/OneDrive - Victoria University of Wellington - STUDENT/GISC 511/ImGraft/TimeSeries Points/Tasman_points2.shp")

## Extract raster value by points
rasValue_5 <- extract(velocity_stack_5, pointCoordinates)
rasValue_10 <- extract(velocity_stack_10, pointCoordinates)
rasValue_20 <- extract(velocity_stack_20, pointCoordinates)
rasValue_30 <- extract(velocity_stack_30, pointCoordinates)

## Combine raster values with points

combinePointValue_5 <- cbind(pointCoordinates,rasValue_5)
combinePointValue_10=cbind(pointCoordinates,rasValue_10)
combinePointValue_20=cbind(pointCoordinates,rasValue_20)
combinePointValue_30=cbind(pointCoordinates,rasValue_30)


## we will use its attribute data
#Attributes_5 <- combinePointValue_5@data
Attributes_10 <- combinePointValue_10@data
Attributes_20 <- combinePointValue_20@data
Attributes_30 <- combinePointValue_30@data

#Attributes_5["Id"] <- c("V 1 - 05 m (m/y)", "V 2 - 05 m (m/y)", "V 3 - 05 m (m/y)", "V 4 - 05 m (m/y)")
Attributes_10["Id"] <- c("V 1 - 10 m (m/y)", "V 2 - 10 m (m/y)", "V 3 - 10 m (m/y)", "V 4 - 10 m (m/y)")
Attributes_20["Id"] <- c("V 1 - 20 m (m/y)", "V 2 - 20 m (m/y)", "V 3 - 20 m (m/y)", "V 4 - 20 m (m/y)")
Attributes_30["Id"] <- c("V 1 - 30 m (m/y)", "V 2 - 30 m (m/y)", "V 3 - 30 m (m/y)", "V 4 - 30 m (m/y)")


Attributes <- rbind(Attributes_10, Attributes_20, Attributes_30) # Attributes_5, 

## We will also change colomn names to only a single date. 

colnames(Attributes)

## First list all filenames that from a pair of imagery that generated this velocity.

filenames <- list.files(workfolder_10, pattern = "*.tif") # they use the same temporal resolution.

filenames <- filenames[nchar(filenames)==21]



## May be we dont need Lat and Lon columns for now

Attributes <- Attributes[-c(2, 3)]


## use only the last 11 to 18 digits as new column which will be good when converting to date and long format.

colnames(Attributes)[-1] <- paste0(substring(filenames, 10, 13), "-", substring(filenames, 14, 15), "-", substring(filenames, 16, 17))


## read rainfall data: 

rainfall <- read.csv("C:/Users/Advice/OneDrive - Victoria University of Wellington - STUDENT/GISC 511/ImGraft/Percipation/wgenf.genform1_proc4.csv", stringsAsFactors=FALSE)

## Filter only two columns


rainfall <- rainfall[c("Date.NZST.","Amount.mm.")]

## Convert dates into date format in R

rainfall$Date.NZST. <- base::as.Date(rainfall$Date.NZST., format="%d-%m-%y")


## Load dplyr and ggplot2 library for further filtering and ploting. 


library(dplyr)
library(ggplot2)
library(tidyverse)


## create a dataframe that contain date, velocity and sum of rainfall by its number of time interval (days)

## Create Another row called "Rain Fall" for storing summed rain fall based on the date interval among imagery.

Attributes[nrow(Attributes)+1,] <- 0

Attributes[nrow(Attributes),"Id"] <- "Rain Fall (mm)" # give it a name

## Note that the first imagery date is "2018-12-15", and the last imagery is 2020-03-15. But we excluded the first imagery from the attribute. 
## now we will store all the date of imagery

im_dates <- c(paste0(substring(filenames[1], 1, 4), "-", substring(filenames[1], 5, 6), "-", substring(filenames[1], 7, 8)), colnames(Attributes)[-1])

## We will filter the rainfall only this period of time.

rainfall <- rainfall %>% filter(Date.NZST. >= first(im_dates) & Date.NZST. <= last(im_dates))

## we will sum rainfall based the time interval. and add that into our velocity matrix named "Attributes" that we created before. 


for (i in 1:(length(im_dates) - 1 )) {
  
  if (i == 1) {  
    
    rain <- rainfall %>% filter(Date.NZST. >= im_dates[i] & Date.NZST. <= im_dates[i+1]) # the first pair we need include the first date of the the first pair "2019-07-25".
    sum <- sum(rain$Amount.mm.)
    
    Attributes[5, i+1] <- sum # add the value to the data.frame that we have. In row 5 and column 2 onward.
    
               } else {
    
    # while the second pair we dont need last date of the pervious pair to sum the data.
    
    rain <- rainfall %>% filter(Date.NZST. > im_dates[i] & Date.NZST. <= im_dates[i+1])
    
    sum <- sum(rain$Amount.mm.)
    
    Attributes[nrow(Attributes), i+1] <- sum }  # add the value to the data.frame that we have. In row 5 and column 2 onward.
  
}



## now we get both Velocity and summed rain data in the same matrix.

Attributes[nrow(Attributes),] # summed Rainfall based on its time interval.


## But we may work abit easier in a long format of the data. We will change wide to long format using this library.

library(reshape2)

Attributes_long <- melt(Attributes, id.vars="Id")

Attributes_long$variable <- as.Date(Attributes_long$variable, format="%Y-%m-%d")



## Change olumns names as well

colnames(Attributes_long) <- c("Variables", "Date", "Values")

## Filter

Attributes_long <- Attributes_long %>% filter(Date >= "2019-08-22" & Date <= "2020-03-15" & Variables != "Rain Fall (mm)")


## Since the number of pairs used in the 5 meter is different, we will do this differently and combine them together
Attributes_5 <- combinePointValue_5@data
Attributes_5["Id"] <- c("V 1 - 05 m (m/y)", "V 2 - 05 m (m/y)", "V 3 - 05 m (m/y)", "V 4 - 05 m (m/y)")
filenames_5 <- list.files(workfolder_5, pattern = "*.tif") # they use the same temporal resolution.
filenames_5 <- filenames_5[nchar(filenames_5)==21]

## May be we dont need Lat and Lon columns for now

Attributes_5 <- Attributes_5[-c(2, 3)]

## use only the last 11 to 18 digits as new column which will be good when converting to date and long format.

colnames(Attributes_5)[-1] <- paste0(substring(filenames_5, 10, 13), "-", substring(filenames_5, 14, 15), "-", substring(filenames_5, 16, 17))

## Convert it to a long format 
Attributes_long_5 <- melt(Attributes_5, id.vars="Id")
Attributes_long_5$variable <- as.Date(Attributes_long_5$variable, format="%Y-%m-%d")

## Change olumns names as well

colnames(Attributes_long_5) <- c("Variables", "Date", "Values")

## combine 5 meter with other resolutions.

Attributes_long <- rbind(Attributes_long, Attributes_long_5)

nrow(Attributes_long_5)
nrow(Attributes_long)

## Now we will try to filter 


Attributes_long_filter_1 <- Attributes_long %>% filter(Variables == "V 1 - 05 m (m/y)" | Variables == "V 1 - 10 m (m/y)" | Variables == "V 1 - 20 m (m/y)" |  Variables == "V 1 - 30 m (m/y)" )
Attributes_long_filter_2 <- Attributes_long %>% filter(Variables == "V 2 - 05 m (m/y)" | Variables == "V 2 - 10 m (m/y)" | Variables == "V 2 - 20 m (m/y)" |  Variables == "V 2 - 30 m (m/y)" )
Attributes_long_filter_3 <- Attributes_long %>% filter(Variables == "V 3 - 05 m (m/y)" | Variables == "V 3 - 10 m (m/y)" | Variables == "V 3 - 20 m (m/y)" |  Variables == "V 3 - 30 m (m/y)" )
Attributes_long_filter_4 <- Attributes_long %>% filter(Variables == "V 4 - 05 m (m/y)" | Variables == "V 4 - 10 m (m/y)" | Variables == "V 4 - 20 m (m/y)" |  Variables == "V 4 - 30 m (m/y)" )



## Filter Rainfall as well

im_dates <- c(paste0(substring(filenames_5[1], 1, 4), "-", substring(filenames_5[1], 5, 6), "-", substring(filenames_5[1], 7, 8)), colnames(Attributes_5)[-1])

## We will filter the rainfall only this period of time.

rainfall <- rainfall %>% filter(Date.NZST. >= first(im_dates) & Date.NZST. <= last(im_dates))




## Now we plot a simple line graph. and use facet graph ##


 p <- ggplot(data=Attributes_long_filter_3,aes(x=Date,y=Values,color=Variables  )) +
      
     #geom_col(data=rainfall, aes(x=Date.NZST., y=Amount.mm.*4), fill="#0f5e9c", color="#0f5e9c", width=0.5) +
     geom_point() +
     geom_line() +
     scale_x_date(breaks = Attributes_long_filter_4$Date) + 
     theme(axis.text.x = element_text(angle = 90)) # + 
   
    # scale_y_continuous(
     
     # Features of the first axis
  #   name = "Velocity (m/year)",
     
     # Add a second axis and specify its features
   #  sec.axis = sec_axis(~./4, name="Rainfall (mm)")
  # )
 
 # 
 My_Theme = theme(
   axis.title.x = element_text(size = 8),
   axis.text.x = element_text(size = 8),
   axis.title.y = element_text(size = 10))
 
 p + My_Theme + facet_grid(rows = vars(Variables))
 


 
 
 
 
 
 
 
 
 
 
 
 
## for writing a csv file we can convert to a proper wide format too.

Attributes_wide <- dcast(Attributes_long, Date ~ Variables , value.var="Values")


## Write it into a csv file for further anlysis

write.csv(Attributes_wide,"C:/Users/Advice/OneDrive - Victoria University of Wellington - STUDENT/GISC 511/ImGraft/Tasman_Deresolution_Velocity/Despatial_resolution_10_20_30_Dec2018_Aug2020.csv", row.names = FALSE)



