### The following codes will be used to extract velocity from the stacked files and plot the result alongside with other full temporal resolution data ####
### As well as rainfall data ###


## load the relevant Library

library(raster)
library(sp)
library(rgdal)
library(gdalUtils)
library(gdalUtilities)
library(RStoolbox)


## Set working directory and define the work folder for 10 meter

setwd("C:/Users/Advice/OneDrive - Victoria University of Wellington - STUDENT/GISC 511/ImGraft/Tasman_Deresolution_Velocity/5 days")

workfolder_2 <- "C:/Users/Advice/OneDrive - Victoria University of Wellington - STUDENT/GISC 511/ImGraft/Velocity_Tiff (1-2, 2-3..)"
workfolder_5 <- "C:/Users/Advice/OneDrive - Victoria University of Wellington - STUDENT/GISC 511/ImGraft/Tasman_Deresolution_Velocity/5 days"
workfolder_16 <- "C:/Users/Advice/OneDrive - Victoria University of Wellington - STUDENT/GISC 511/ImGraft/Tasman_Deresolution_Velocity/16 days"
workfolder_30 <- "C:/Users/Advice/OneDrive - Victoria University of Wellington - STUDENT/GISC 511/ImGraft/Tasman_Deresolution_Velocity/30 days"

## Read all the stacked files

## Read the stacked raster that contains all velocity compared between scences generated by using Matlab - Imgraft Package.
velocity_stack_2   <- stack(file.path(workfolder_2, "velocity_stack.tif"))
velocity_stack_5   <- stack(file.path(workfolder_5, "velocity_stack.tif"))
velocity_stack_16  <- stack(file.path(workfolder_16, "velocity_stack.tif"))
velocity_stack_30  <- stack(file.path(workfolder_30, "velocity_stack.tif"))

## read our interested 4 points in shapefiles.

pointCoordinates=readOGR("C:/Users/Advice/OneDrive - Victoria University of Wellington - STUDENT/GISC 511/ImGraft/TimeSeries Points/Tasman_points2.shp")

## Extract raster value by points
rasValue_2 <- extract(velocity_stack_2, pointCoordinates)
rasValue_5 <- extract(velocity_stack_5, pointCoordinates)
rasValue_16 <- extract(velocity_stack_16, pointCoordinates)
rasValue_30 <- extract(velocity_stack_30, pointCoordinates)


## Combine raster values with points

combinePointValue_2 <- cbind(pointCoordinates,rasValue_2)
combinePointValue_5 <- cbind(pointCoordinates,rasValue_5)
combinePointValue_16 <- cbind(pointCoordinates,rasValue_16)
combinePointValue_30 <- cbind(pointCoordinates,rasValue_30)


## we will use its attribute data
Attributes_2 <- combinePointValue_2@data
Attributes_5 <- combinePointValue_5@data
Attributes_16 <- combinePointValue_16@data
Attributes_30 <- combinePointValue_30@data

Attributes_2["Id"] <- c("V 1 - 2 d (m/y)", "V 2 - 02 d (m/y)", "V 3 - 02 d (m/y)", "V 4 - 02 d (m/y)")
Attributes_5["Id"] <- c("V 1 - 5 d (m/y)", "V 2 - 05 d (m/y)", "V 3 - 05 d (m/y)", "V 4 - 05 d (m/y)")
Attributes_16["Id"] <- c("V 1 - 16 d (m/y)", "V 2 - 16 d (m/y)", "V 3 - 16 d (m/y)", "V 4 - 16 d (m/y)")
Attributes_30["Id"] <- c("V 1 - 30 d (m/y)", "V 2 - 30 d (m/y)", "V 3 - 30 d (m/y)", "V 4 - 30 d (m/y)")

## Remove Lat & Lon Columns. 
Attributes_2 <- Attributes_2[-c(2, 3)]
Attributes_5 <- Attributes_5[-c(2, 3)]
Attributes_16 <- Attributes_16[-c(2, 3)]
Attributes_30 <- Attributes_30[-c(2, 3)]

## We will also change colomn names to only a single date. 
colnames(Attributes_2) 
colnames(Attributes_5) 
colnames(Attributes_16) 
colnames(Attributes_30)


## First list all filenames that from a pair of imagery that generated this velocity.
 # we will get the date from the image names

filenames_2 <- list.files(workfolder_2, pattern = "*.tif") 
filenames_5 <- list.files(workfolder_5, pattern = "*.tif") 
filenames_16 <- list.files(workfolder_16, pattern = "*.tif")
filenames_30 <- list.files(workfolder_30, pattern = "*.tif") 

filenames_2 <- filenames_2[nchar(filenames_2)==21]
filenames_5 <- filenames_5[nchar(filenames_5)==21]
filenames_16 <- filenames_16 [nchar(filenames_16)==21]
filenames_30 <- filenames_30[nchar(filenames_30)==21]

## Change column names into dates.
colnames(Attributes_2) [-1] <- paste0(substring(filenames_2, 10, 13), "-", substring(filenames_2, 14, 15), "-", substring(filenames_2, 16, 17))
colnames(Attributes_5) [-1] <- paste0(substring(filenames_5, 10, 13), "-", substring(filenames_5, 14, 15), "-", substring(filenames_5, 16, 17))
colnames(Attributes_16) [-1] <- paste0(substring(filenames_16, 10, 13), "-", substring(filenames_16, 14, 15), "-", substring(filenames_16, 16, 17))
colnames(Attributes_30) [-1] <- paste0(substring(filenames_30, 10, 13), "-", substring(filenames_30, 14, 15), "-", substring(filenames_30, 16, 17))

## Add another row to each dataset ( rainfall)
Attributes_2[5, 1] <- "Rainfall (mm)"
Attributes_5[5, 1] <- "Rainfall (mm)"
Attributes_16[5,1] <- "Rainfall (mm)"
Attributes_30[5,1] <- "Rainfall (mm)"

## read rainfall data: 


library(dplyr)
library(ggplot2)
library(tidyverse)


rainfall <- read.csv("C:/Users/Advice/OneDrive - Victoria University of Wellington - STUDENT/GISC 511/ImGraft/Percipation/wgenf.genform1_proc4.csv", stringsAsFactors=FALSE)
rainfall <- rainfall[c("Date.NZST.","Amount.mm.")] # Filter only two columns
rainfall$Date.NZST. <- base::as.Date(rainfall$Date.NZST., format="%d-%m-%y") # Convert dates into date format in R

## All dates of imagery
im_dates_2 <- c(paste0(substring(filenames_2[1], 1, 4), "-", substring(filenames_2[1], 5, 6), "-", substring(filenames_2[1], 7, 8)), colnames(Attributes_2)[-1])
im_dates_5 <- c(paste0(substring(filenames_5[1], 1, 4), "-", substring(filenames_5[1], 5, 6), "-", substring(filenames_5[1], 7, 8)), colnames(Attributes_5)[-1])
im_dates_16 <- c(paste0(substring(filenames_16[1], 1, 4), "-", substring(filenames_16[1], 5, 6), "-", substring(filenames_16[1], 7, 8)), colnames(Attributes_16)[-1])
im_dates_30 <- c(paste0(substring(filenames_30[1], 1, 4), "-", substring(filenames_30[1], 5, 6), "-", substring(filenames_30[1], 7, 8)), colnames(Attributes_30)[-1])

## Filter rainfall

rainfall_2 <- rainfall %>% filter(Date.NZST. >= first(im_dates_2) & Date.NZST. <= last(im_dates_2))
rainfall_5 <- rainfall %>% filter(Date.NZST. >= first(im_dates_5) & Date.NZST. <= last(im_dates_5))
rainfall_16 <- rainfall %>% filter(Date.NZST. >= first(im_dates_16) & Date.NZST. <= last(im_dates_16))
rainfall_30 <- rainfall %>% filter(Date.NZST. >= first(im_dates_30) & Date.NZST. <= last(im_dates_30))


## Sum rainfall based on time inter of each pair of imagery and append them into each velocity dataset..

## 2 days
for (i in 1:(length(im_dates_2) - 1 )) {
  if (i == 1) {
    rain <- rainfall_2 %>% filter(Date.NZST. >= im_dates_2[i] & Date.NZST. <= im_dates_2[i+1]) # the first pair we need include the first date.
    sum <- sum(rain$Amount.mm.)
    Attributes_2[5, i+1] <- sum # add the value to the data.frame that we have. In row 5 and column 2 onward.
    
  } else {
    # while the second pair we dont need last date of the pervious pair to sum the data.
    rain <- rainfall_2 %>% filter(Date.NZST. > im_dates_2[i] & Date.NZST. <= im_dates_2[i+1]) # do not sum the first of the second pair onward.
    sum <- sum(rain$Amount.mm.)
    Attributes_2[5, i+1] <- sum }  # add the value to the data.frame that we have. In row 5 and column 2 onward.
}

## 5 days

for (i in 1:(length(im_dates_5) - 1 )) {
  if (i == 1) {
    rain <- rainfall_5 %>% filter(Date.NZST. >= im_dates_5[i] & Date.NZST. <= im_dates_5[i+1]) # the first pair we need include the first date.
    sum <- sum(rain$Amount.mm.)
    Attributes_5[5, i+1] <- sum # add the value to the data.frame that we have. In row 5 and column 2 onward.
    
  } else {
    # while the second pair we dont need last date of the pervious pair to sum the data.
    rain <- rainfall_5 %>% filter(Date.NZST. > im_dates_5[i] & Date.NZST. <= im_dates_5[i+1]) # do not sum the first of the second pair onward.
    sum <- sum(rain$Amount.mm.)
    Attributes_5[5, i+1] <- sum }  # add the value to the data.frame that we have. In row 5 and column 2 onward.
}

## 16 days

for (i in 1:(length(im_dates_16) - 1 )) {
  if (i == 1) {
    rain <- rainfall_16 %>% filter(Date.NZST. >= im_dates_16[i] & Date.NZST. <= im_dates_16[i+1]) # the first pair we need include the first date.
    sum <- sum(rain$Amount.mm.)
    Attributes_16[5, i+1] <- sum # add the value to the data.frame that we have. In row 5 and column 2 onward.
    
  } else {
    # while the second pair we dont need last date of the pervious pair to sum the data.
    rain <- rainfall_16 %>% filter(Date.NZST. > im_dates_16[i] & Date.NZST. <= im_dates_16[i+1]) # do not sum the first of the second pair onward.
    sum <- sum(rain$Amount.mm.)
    Attributes_16[5, i+1] <- sum }  # add the value to the data.frame that we have. In row 5 and column 2 onward.
}

## 30 days
for (i in 1:(length(im_dates_30) - 1 )) {
  if (i == 1) {
    rain <- rainfall_30 %>% filter(Date.NZST. >= im_dates_30[i] & Date.NZST. <= im_dates_30[i+1]) # the first pair we need include the first date.
    sum <- sum(rain$Amount.mm.)
    Attributes_30[5, i+1] <- sum # add the value to the data.frame that we have. In row 5 and column 2 onward.
    
  } else {
    # while the second pair we dont need last date of the pervious pair to sum the data.
    rain <- rainfall_30 %>% filter(Date.NZST. > im_dates_30[i] & Date.NZST. <= im_dates_30[i+1]) # do not sum the first of the second pair onward.
    sum <- sum(rain$Amount.mm.)
    Attributes_30[5, i+1] <- sum }  # add the value to the data.frame that we have. In row 5 and column 2 onward.
}


## convert them into long-format

library(reshape2)
Attributes_long_2 <- melt(Attributes_2, id.vars="Id")
Attributes_long_5 <- melt(Attributes_5, id.vars="Id")
Attributes_long_16 <- melt(Attributes_16, id.vars="Id")
Attributes_long_30 <- melt(Attributes_30, id.vars="Id")

Attributes_long_2$variable <- as.Date(Attributes_long_2$variable, format="%Y-%m-%d") # convert to date format
Attributes_long_5$variable <- as.Date(Attributes_long_5$variable, format="%Y-%m-%d") # convert to date format
Attributes_long_16$variable <- as.Date(Attributes_long_16$variable, format="%Y-%m-%d") # convert to date format
Attributes_long_30$variable <- as.Date(Attributes_long_30$variable, format="%Y-%m-%d") # convert to date format

colnames(Attributes_long_2) <- c("Variables", "Date", "Values") # Change column names
colnames(Attributes_long_5) <- c("Variables", "Date", "Values") # Change column names
colnames(Attributes_long_16) <- c("Variables", "Date", "Values") # Change column names
colnames(Attributes_long_30) <- c("Variables", "Date", "Values") # Change column names



## Plot each dataset with rainfalldata


# first filter it

Attributes_long_2 <- Attributes_long_2 %>% filter(Date > "2019-01-16" & Date <= "2020-03-30", Variables != "Rainfall (mm)")
Attributes_long_5 <- Attributes_long_5 %>% filter(Date > "2019-01-16" & Date <= "2020-03-30", Variables != "Rainfall (mm)")
Attributes_long_16 <- Attributes_long_16 %>% filter(Date > "2019-01-16" & Date <= "2020-03-30", Variables != "Rainfall (mm)")
Attributes_long_30 <- Attributes_long_30 %>% filter(Date > "2019-01-16" & Date <= "2020-03-30", Variables != "Rainfall (mm)")

rainfall_2 <- rainfall_2 %>% filter(Date.NZST. >= "2019-01-16" & Date.NZST. <= "2020-03-30")

## Filter by point location

# velocity point 1

long_point_1 <- rbind(Attributes_long_2[which(Attributes_long_2$Variables == "V 1 - 02 d (m/y)"),],
                      Attributes_long_5[which(Attributes_long_5$Variables == "V 1 - 05 d (m/y)"),],
                      Attributes_long_16[which(Attributes_long_16$Variables == "V 1 - 16 d (m/y)"),],
                      Attributes_long_30[which(Attributes_long_30$Variables == "V 1 - 30 d (m/y)"),])

long_point_2 <- rbind(Attributes_long_2[which(Attributes_long_2$Variables == "V 2 - 02 d (m/y)"),],
                      Attributes_long_5[which(Attributes_long_5$Variables == "V 2 - 05 d (m/y)"),],
                      Attributes_long_16[which(Attributes_long_16$Variables == "V 2 - 16 d (m/y)"),],
                      Attributes_long_30[which(Attributes_long_30$Variables == "V 2 - 30 d (m/y)"),])

long_point_3 <- rbind(Attributes_long_2[which(Attributes_long_2$Variables == "V 3 - 02 d (m/y)"),],
                      Attributes_long_5[which(Attributes_long_5$Variables == "V 3 - 05 d (m/y)"),],
                      Attributes_long_16[which(Attributes_long_16$Variables == "V 3 - 16 d (m/y)"),],
                      Attributes_long_30[which(Attributes_long_30$Variables == "V 3 - 30 d (m/y)"),])
long_point_4 <- rbind(Attributes_long_2[which(Attributes_long_2$Variables == "V 4 - 02 d (m/y)"),],
                      Attributes_long_5[which(Attributes_long_5$Variables == "V 4 - 05 d (m/y)"),],
                      Attributes_long_16[which(Attributes_long_16$Variables == "V 4 - 16 d (m/y)"),],
                      Attributes_long_30[which(Attributes_long_30$Variables == "V 4 - 30 d (m/y)"),])


#long_point_1[which(long_point_1$Variables=="V 1 - 2 d (m/y)"),1] <- "V 1 - 02 d (m/y)"
#long_point_1[which(long_point_1$Variables=="V 1 - 5 d (m/y)"),1] <- "V 1 - 05 d (m/y)"

#long_point_2[which(long_point_2$Variables=="V 2 - 2 d (m/y)"),1] <- "V 2 - 02 d (m/y)"
#long_point_2[which(long_point_2$Variables=="V 2 - 5 d (m/y)"),1] <- "V 2 - 05 d (m/y)"

#long_point_3[which(long_point_3$Variables=="V 3 - 2 d (m/y)"),1] <- "V 3 - 02 d (m/y)"
#long_point_3[which(long_point_3$Variables=="V 3 - 5 d (m/y)"),1] <- "V 3 - 05 d (m/y)"

#long_point_4[which(long_point_4$Variables=="V 4 - 2 d (m/y)"),1] <- "V 4 - 02 d (m/y)"
#long_point_4[which(long_point_4$Variables=="V 4 - 5 d (m/y)"),1] <- "V 4 - 05 d (m/y)"





## Convert into wide format ( new wide format for saving in .csv and easier for ploting in Excel)
Attributes_wide_2 <- dcast(Attributes_long_2, Date ~ Variables , value.var="Values")
Attributes_wide_5 <- dcast(Attributes_long_5, Date ~ Variables , value.var="Values")
Attributes_wide_16 <- dcast(Attributes_long_16, Date ~ Variables , value.var="Values")
Attributes_wide_30 <- dcast(Attributes_long_30, Date ~ Variables , value.var="Values")



## Save the outputs as csv files for further use. 
write.csv(Attributes_wide_2,paste0(workfolder_2, "/Velocity_2days_re_Tasman.csv"), row.names = FALSE)
write.csv(Attributes_wide_5,paste0(workfolder_5, "/Velocity_5days_re_Tasman.csv"), row.names = FALSE)
write.csv(Attributes_wide_16,paste0(workfolder_16, "/Velocity_16days_re_Tasman.csv"), row.names = FALSE)
write.csv(Attributes_wide_30,paste0(workfolder_30, "/Velocity_30days_re_Tasman.csv"), row.names = FALSE)

# Velocity Point 1


pp <- ggplot(data=long_point_1,aes(x=Date,y=Values,color=Variables )) +
  geom_col(data=rainfall_2, aes(x=Date.NZST., y=Amount.mm.*2), fill="#0f5e9c", color="#0f5e9c", width=0.5) +
  geom_point() +
  geom_line() +
  scale_x_date(breaks = Attributes_long_5$Date) + 
  theme(axis.text.x = element_text(angle = 90)) + 
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Velocity (m/year)",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~./2, name="Rainfall (mm)")
  )

# 
My_Theme = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 6),
  axis.title.y = element_text(size = 10))

pp + My_Theme  + facet_grid(rows = vars(Variables))



# Velocity Point 2


pp <- ggplot(data=long_point_2,aes(x=Date,y=Values,color=Variables )) +
  geom_col(data=rainfall_2, aes(x=Date.NZST., y=Amount.mm.*2), fill="#0f5e9c", color="#0f5e9c", width=0.5) +
  geom_point() +
  geom_line() +
  scale_x_date(breaks = Attributes_long_5$Date) + 
  theme(axis.text.x = element_text(angle = 90)) + 
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Velocity (m/year)",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~./2, name="Rainfall (mm)")
  )


My_Theme = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 6),
  axis.title.y = element_text(size = 10))

pp + My_Theme  + facet_grid(rows = vars(Variables))



# Velocity Point 3

pp <- ggplot(data=long_point_3,aes(x=Date,y=Values,color=Variables )) +
  geom_col(data=rainfall_2, aes(x=Date.NZST., y=Amount.mm.*2), fill="#0f5e9c", color="#0f5e9c", width=0.5) +
  geom_point() +
  geom_line() +
  scale_x_date(breaks = Attributes_long_5$Date) + 
  theme(axis.text.x = element_text(angle = 90)) + 
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Velocity (m/year)",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~./2, name="Rainfall (mm)")
  )

# 
My_Theme = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 6),
  axis.title.y = element_text(size = 10))

pp + My_Theme  + facet_grid(rows = vars(Variables))




# Point location 4


pp <- ggplot(data=long_point_4,aes(x=Date,y=Values,color=Variables )) +
  geom_col(data=rainfall_2, aes(x=Date.NZST., y=Amount.mm.*2), fill="#0f5e9c", color="#0f5e9c", width=0.5) +
  geom_point() +
  geom_line() +
  scale_x_date(breaks = Attributes_long_5$Date) + 
  theme(axis.text.x = element_text(angle = 90)) + 
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Velocity (m/year)",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~./2, name="Rainfall (mm)")
  )

# 
My_Theme = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 6),
  axis.title.y = element_text(size = 10))

pp + My_Theme  + facet_grid(rows = vars(Variables))



## plot without rain data

# Velocity Point 1


pp <- ggplot(data=long_point_1,aes(x=Date,y=Values,color=Variables )) +
  geom_point() +
  geom_line() +
  scale_x_date(breaks = Attributes_long_5$Date) + 
  theme(axis.text.x = element_text(angle = 90)) 
  
# 
My_Theme = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 6),
  axis.title.y = element_text(size = 10))

pp + My_Theme  + facet_grid(rows = vars(Variables))



# Velocity Point 2


pp <- ggplot(data=long_point_2,aes(x=Date,y=Values,color=Variables )) +
  
  geom_point() +
  geom_line() +
  scale_x_date(breaks = Attributes_long_5$Date) + 
  theme(axis.text.x = element_text(angle = 90)) 
  

My_Theme = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 6),
  axis.title.y = element_text(size = 10))

pp + My_Theme  + facet_grid(rows = vars(Variables))



# Velocity Point 3

pp <- ggplot(data=long_point_3,aes(x=Date,y=Values,color=Variables )) +
  geom_point() +
  geom_line() +
  scale_x_date(breaks = Attributes_long_5$Date) + 
  theme(axis.text.x = element_text(angle = 90)) 
  

# 
My_Theme = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 6),
  axis.title.y = element_text(size = 10))

pp + My_Theme  + facet_grid(rows = vars(Variables))




# Point location 4


pp <- ggplot(data=long_point_4,aes(x=Date,y=Values,color=Variables )) +
  
  geom_point() +
  geom_line() +
  scale_x_date(breaks = Attributes_long_5$Date) + 
  theme(axis.text.x = element_text(angle = 90)) 

# 
My_Theme = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 6),
  axis.title.y = element_text(size = 10))

pp + My_Theme  + facet_grid(rows = vars(Variables))













## un_useful this part. will not work properly. 

## combine those three datasets together.

Attributes_long_combined <- rbind(Attributes_long_5, Attributes_long_16, Attributes_long_30)

## Plot all datasets together.

p <- ggplot(data=Attributes_long_combined,aes(x=Date,y=Values,color=Variables  )) +
  geom_point() +
  geom_line()

p + facet_grid(rows = vars(Variables))

## write csv file for further usage.

write.csv(Attributes_long_combined,"C:/Users/Advice/OneDrive - Victoria University of Wellington - STUDENT/GISC 511/ImGraft/Tasman_Deresolution_Velocity/Long_combined_Velocity_De_temporal_resolution_Tasman_Dec2018_Aug2020.csv", row.names = FALSE)







